export const ADD_TIMBER_CALCULATION_DATA = "ADD_TIMBER_CALCULATION_DATA";
export const CHANGE_APP_LANGUAGE = "CHANGE_APP_LANGUAGE";
export const LEFT_DRAWER_CLOSE = "LEFT_DRAWER_CLOSE";
export const ADD_OR_EDIT_MODE = "ADD_OR_EDIT_MODE";
export const ADD_CALCULATED_DATA = "ADD_CALCULATED_DATA";
export const ENABLE_DISPLAY_RESULTS = "ENABLE_DISPLAY_RESULTS";
export const SET_TABLE_SELECTED_ELEMENTS = "SET_TABLE_SELECTED_ELEMENTS";
export const DELETE_ITEMS = "DELETE_ITEMS";
